
from torch import Tensor, FloatTensor, LongTensor
from typing import overload, List
@overload
def pack_sequence(sequences : List[FloatTensor]) -> FloatTensor: ...
@overload
def pack_sequence(sequences : List[LongTensor]) -> LongTensor: ...
@overload
def pack_sequence(sequences : List[Tensor]) -> Tensor: ...
@overload
def pad_sequence(sequences : List[FloatTensor], batch_first=False, padding_value=0) \
    -> FloatTensor: ...
@overload
def pad_sequence(sequences : List[LongTensor], batch_first=False, padding_value=0) \
    -> LongTensor: ...
@overload
def pad_sequence(sequences : List[Tensor], batch_first=False, padding_value=0) \
    -> Tensor: ...
