
from torch import Tensor, FloatTensor, LongTensor
from typing import overload

@overload
def relu(t : FloatTensor) -> FloatTensor : ...
@overload
def relu(t : Tensor) -> Tensor : ...
@overload
def mse_loss(inp: FloatTensor, target: FloatTensor) -> FloatTensor: ...
@overload
def mse_loss(inp: Tensor, target: Tensor) -> FloatTensor: ...
def one_hot(t: LongTensor, num_classes: int) -> LongTensor: ...
